services:
  web:
    build:
      context: .
      target: deploy
      dockerfile: docker/Dockerfile
    container_name: web
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      - MONGO_URL=${MONGO_URL}
      - REDIS_ADDR=${REDIS_ADDR}
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=analyzer
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - '6379:6379'
    healthcheck:
        test: [ "CMD", "redis-cli", "ping" ]
        interval: 10s
        timeout: 5s
        retries: 5
