openapi: 3.0.0
info:
  title: Web Analyzer API
  description: API for user registration, authentication, and website analysis.
  version: 1.0.0
servers:
  - url: http://localhost:8000/api

paths:
  /auth/register:
    post:
      summary: Registers a new user
      requestBody:
        description: Username and password for registration
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: tharinda22
                password:
                  type: string
                  example: Tharinda@123
              required:
                - username
                - password
      responses:
        '200':
          description: Registration successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token for the new user
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        field:
                          type: string
                        message:
                          type: string
                  message:
                    type: string
                    example: validation failed

  /auth/login:
    post:
      summary: Authenticates a user
      requestBody:
        description: Username and password for login
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: tharinda22
                password:
                  type: string
                  example: Tharinda@123
              required:
                - username
                - password
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token for the authenticated user
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string

  /analyse:
    post:
      summary: Submits a website URL for analysis
      security:
        - bearerAuth: []
      requestBody:
        description: URL of the website to be analyzed
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  format: uri
                  example: https://golangci-lint.run/
      responses:
        '200':
          description: Website analysis result or pending status
          content:
            application/json:
              schema:
                type: object
                properties:
                  ID:
                    type: integer
                  WebsiteID:
                    type: integer
                  Data:
                    type: object
                    properties:
                      links:
                        type: object
                        properties:
                          external_links:
                            type: integer
                          internal_links:
                            type: integer
                          inaccessible_links:
                            type: integer
                      page_title:
                        type: string
                      html_version:
                        type: string
                      headings_count:
                        type: object
                        properties:
                          h1:
                            type: integer
                          h2:
                            type: integer
                          h3:
                            type: integer
                          h4:
                            type: integer
                          h5:
                            type: integer
                          h6:
                            type: integer
                      contains_login_form:
                        type: boolean
                      analysis_completed_at:
                        type: string
                        format: date-time
                  Status:
                    type: string
                    example: completed
                  CreatedAt:
                    type: string
                    format: date-time
                  UpdatedAt:
                    type: string
                    format: date-time
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        field:
                          type: string
                        message:
                          type: string
                  message:
                    type: string
                    example: validation failed

  /websitesbyID/{id}:
    get:
      summary: Retrieves detailed information for a specific website by its ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The ID of the website to retrieve
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Details of the specified website
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  url:
                    type: string
                    format: uri
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                  analytics:
                    type: object
                    properties:
                      ID:
                        type: integer
                      WebsiteID:
                        type: integer
                      Data:
                        type: object
                        properties:
                          links:
                            type: object
                            properties:
                              external_links:
                                type: integer
                              internal_links:
                                type: integer
                              inaccessible_links:
                                type: integer
                          page_title:
                            type: string
                          html_version:
                            type: string
                          headings_count:
                            type: object
                            properties:
                              h1:
                                type: integer
                              h2:
                                type: integer
                              h3:
                                type: integer
                              h4:
                                type: integer
                              h5:
                                type: integer
                              h6:
                                type: integer
                          contains_login_form:
                            type: boolean
                          analysis_completed_at:
                            type: string
                            format: date-time
                      status:
                        type: string
                      CreatedAt:
                        type: string
                        format: date-time
                      UpdatedAt:
                        type: string
                        format: date-time
        '404':
          description: Website not found

  /websites:
    get:
      summary: Retrieves a list of all websites with their respective information
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of websites
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    url:
                      type: string
                      format: uri
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
